version: '2'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code/
      - /code/venv/
    ports:
      - 7730:8080
  redis:
    image: redis:5.0.6-alpine
