FROM python:3.7-stretch

RUN curl -L https://deb.nodesource.com/setup_13.x | bash -
RUN apt install nodejs
RUN npm i -g nodemon

WORKDIR /code/

COPY requirements.txt requirements.txt
RUN python -m venv venv
RUN venv/bin/pip install -r requirements.txt

COPY app app
COPY gather.py .

EXPOSE 8080
ENTRYPOINT ["nodemon", "--exec", "venv/bin/python", "gather.py"]
